storage:
  host: mysql
  port: 3306
  user: root
  password: mysql_password1
  database: directory_logger
directories:
  - path: ./tmp/test1
    include_regexp:
      - .*.txt$
    exclude_regexp:
      - .*a.txt$
  - path: ./tmp/test2
    include_regexp:
      - .*k.txt$
      - .*q.txt$